# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'

# Layout rules
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

# Style rules
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

# Metrics rules
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 5

# Naming rules
Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/MethodParameterName:
  AllowedNames:
    - 'a'
    - 'b'
    - 'i'
    - 'j'
    - 'k'
    - 'x'
    - 'y'
    - 'z'

# Rails specific rules
Rails/ApplicationRecord:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationMailer:
  Enabled: true

Rails/ApplicationController:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/SafeNavigation:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Rails/IndexBy:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantForeignKey:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/ContentTag:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

# Performance rules
Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

# Security rules
Security/YAMLLoad:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

# Bundler rules
Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

# Gemspec rules
Gemspec/RequireMFA:
  Enabled: true

Gemspec/RequiredRubyVersion:
  Enabled: true